import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import MultipleIput from "@/components/organisms/MultipleInput";
import { listState } from "@/recoils/ListAdd/atoms";
import { useRecoilState } from "recoil";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [list, setList] = useRecoilState(listState);

  const addNewList = () => {
    let data = [...list];
    data.push('');
    setList(data);
  }

  const deleteList = (index: number) => {
    let data = [...list];
    data.splice(index,1);
    setList(data);
  }

  const changeValue = (value: string, index: number) => {
    let data = [...list];
    data[index] = value;
    setList(data);
  }

  return (
    <>
      <Head>
        <title>Sqouts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <MultipleIput
            list={list}
            onChange={(value: string, index: number) => changeValue(value,index)}
            onClickAdd={addNewList}
            onClickMin={(index: number)=> deleteList(index)}
          />
        </div>
      </main>
    </>
  );
}
